import {secrets} from './secrets'

var API_KEY = secrets.API_KEY
var AUTH_DOMAIN = secrets.AUTH_DOMAIN;
var PROJECT_ID = secrets.PROJECT_ID;
var STORAGE_BUCKET = secrets.STORAGE_BUCKET;
var MESSAGING_SENDER_ID = secrets.MESSAGING_SENDER_ID;
var APP_ID = secrets.APP_ID;
var MEASUREMENT_ID = secrets.MEASUREMENT_ID;

export {API_KEY, AUTH_DOMAIN, PROJECT_ID, STORAGE_BUCKET, MESSAGING_SENDER_ID, APP_ID, MEASUREMENT_ID}




